apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: eye-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio.eye-platform.svc.cluster.local:9000
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secretkey
        - name: BACKEND_STORE_URI
          value: postgresql://postgres:postgres@postgres.eye-platform.svc.cluster.local:5432/mlflow
        - name: ARTIFACT_ROOT
          value: s3://eyemodels
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: eye-platform
spec:
  selector:
    app: mlflow
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
  externalIPs:
    - {{ .Values.mlflow.externalIP }}
