services:
  eye-fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: eye-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    dns:
      - 8.8.8.8 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: your-access-key
      MINIO_ROOT_PASSWORD: your-secret-key
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - monitor-net

  minio_init:
    image: minio/mc
    container_name: minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio http://minio:9000 your-access-key your-secret-key &&
      mc mb -p myminio/production || echo 'Bucket already exists'
      "
    networks:
      - monitor-net

  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    ports:
      - "8080:8080"
    networks:
      - monitor-net

volumes:
  minio_data:

networks:
  monitor-net:
    driver: bridge
