global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eye_serve'
    static_configs:
      - targets: ['${SERVE_IP}:8080']
    metrics_path: /metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['${MONITOR_IP}:9100']
