---
- name: Post-Kubernetes Setup for Eye Diagnosis Cluster
  hosts: node1
  become: yes

  tasks:
    - name: Enable kubectl for user 'cc'
      shell: |
        mkdir -p /home/cc/.kube
        cp /etc/kubernetes/admin.conf /home/cc/.kube/config
        chown -R cc:cc /home/cc/.kube

    - name: Add user 'cc' to docker group
      user:
        name: cc
        groups: docker
        append: yes

    - name: Disable IPv6 system-wide
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Apply DNS CoreDNS patch for Chameleon compatibility
      shell: |
        kubectl -n kube-system patch configmap coredns \
        --type merge \
        -p '{"data":{"Corefile":".:53 {\n    errors\n    health\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods insecure\n       fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . /etc/resolv.conf\n    cache 30\n    loop\n    reload\n    loadbalance\n}"}}'

    - name: Install ArgoCD, Argo Workflows, and Argo Events
      shell: |
        kubectl create namespace argocd || true
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        kubectl create namespace argo || true
        kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/stable/manifests/install.yaml
        kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-events/stable/manifests/install.yaml

    - name: Copy ArgoCD admin password secret to other namespaces
      shell: |
        kubectl get secret argocd-initial-admin-secret -n argocd -o yaml | sed 's/namespace: argocd/namespace: argo/' | kubectl apply -f -
