{
 "title": "Eye Disease Monitoring",
 "refresh": "5s",
 "panels": [
  {
   "title": "API Latency (ms)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "rate(inference_latency_seconds_sum[1m]) / rate(inference_latency_seconds_count[1m]) * 1000"
    }
   ]
  },
  {
   "title": "Prediction Count",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "increase(predictions_total[5m])"
    }
   ]
  },
  {
   "title": "Avg Confidence",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "avg_over_time(model_confidence_score[5m])"
    }
   ]
  },
  {
   "title": "Drift Alert",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max_over_time(drift_alert[5m])" }
   ]
  }
 ]
}