FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY fast_api.py .
COPY MobileNetV3.pth .

CMD ["uvicorn", "fast_api:app", "--host", "0.0.0.0", "--port", "8000"]
