version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  webserver:
    image: apache/airflow:2.7.0
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__DEFAULT_USER_EMAIL: airflow@example.com
      AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD: airflow
      AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME: airflow
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    command: webserver

  scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      - webserver
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler