services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - airflow-net

  airflow:
    image: apache/airflow:2.7.1
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME: airflow@example.com
      AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD: airflow
    volumes:
      - /mnt/block/airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username airflow@example.com --password airflow --firstname Air --lastname Flow --role Admin --email airflow@example.com &&
      airflow webserver"
    networks:
      - airflow-net

networks:
  airflow-net:
    driver: bridge

volumes:
  postgres_db: