---
- name: Register Eye Production App with ArgoCD
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Detect external IP of node1
      set_fact:
        external_ip: "{{ lookup('pipe', \"openstack floating ip list -f value -c 'Floating IP Address' | grep '^10.56'\") }}"

    - name: Add production app to ArgoCD
      command: >
        argocd app create eyeapp-production
        --repo https://github.com/your-org/eye-disease-detection
        --path k8s/production
        --dest-namespace eye-production
        --dest-server https://kubernetes.default.svc
        --directory-recurse
        --helm-set-string externalIP="{{ external_ip }}"
        --sync-policy automated
      environment:
        ARGOCD_OPTS: "--insecure"
