- name: Register ArgoCD application: platform
  hosts: localhost
  tasks:
    - name: Create platform app in ArgoCD
      shell: |
        argocd app create platform \
          --repo https://github.com/rushxbh910/Automated-Eye-Disease-Detection-System.git \
          --path k8s/platform \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace gourmetgram-platform \
          --directory-recurse \
          --upsert \
          --yes
