- name: Register ArgoCD application: staging
  hosts: localhost
  tasks:
    - name: Create staging app in ArgoCD
      shell: |
        argocd app create staging \
          --repo https://github.com/rushxbh910/Automated-Eye-Disease-Detection-System.git \
          --path k8s/staging \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace gourmetgram-staging \
          --directory-recurse \
          --upsert \
          --yes
