- name: Register ArgoCD application: production
  hosts: localhost
  tasks:
    - name: Create production app in ArgoCD
      shell: |
        argocd app create production \
          --repo https://github.com/rushxbh910/Automated-Eye-Disease-Detection-System.git \
          --path k8s/production \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace gourmetgram-production \
          --directory-recurse \
          --upsert \
          --yes
