- name: Register ArgoCD application: canary
  hosts: localhost
  tasks:
    - name: Create canary app in ArgoCD
      shell: |
        argocd app create canary \
          --repo https://github.com/rushxbh910/Automated-Eye-Disease-Detection-System.git \
          --path k8s/canary \
          --dest-server https://kubernetes.default.svc \
          --dest-namespace gourmetgram-canary \
          --directory-recurse \
          --upsert \
          --yes
