- name: Run initial model build using Argo Workflows
  hosts: localhost
  tasks:
    - name: Submit build-initial workflow
      shell: |
        argo submit --watch \
          --namespace argo \
          --serviceaccount argo \
          --generate-name kaniko-eye-initial- \
          -f /workflows/build-initial.yaml