- name: Register Argo Workflows templates
  hosts: localhost
  tasks:
    - name: Apply train-model workflow template
      shell: kubectl apply -f /workflows/train-model.yaml -n argo

    - name: Apply build-container-image workflow template
      shell: kubectl apply -f /workflows/build-container-image.yaml -n argo

    - name: Apply deploy-container-image workflow template
      shell: kubectl apply -f /workflows/deploy-container-image.yaml -n argo

    - name: Apply promote-model workflow template
      shell: kubectl apply -f /workflows/promote-model.yaml -n argo