---
- name: Pre-Kubernetes Configuration for Eye Diagnosis Cluster
  hosts: all
  become: yes
  tasks:
    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Configure Docker to allow insecure local registry
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries" : ["registry.kube-system.svc.cluster.local:5000"]
          }

    - name: Restart Docker
      service:
        name: docker
        state: restarted
