all:
  vars:
    ansible_user: cc
    ansible_ssh_private_key_file: ~/.ssh/project_24.pem
  hosts:
    training_node:
      ansible_host: "{{ training_floating_ip }}"
    serving_node:
      ansible_host: "{{ serving_floating_ip }}"