- name: Common Setup on All Nodes
  hosts: all
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - git

# === TRAINING NODE SETUP ===
- name: Setup and Run Model Trainer
  hosts: training_node
  become: true
  tasks:
    - name: Copy trainer code
      copy:
        src: ../trainer/
        dest: /home/cc/trainer/
        owner: cc
        group: cc
        mode: '0755'

    - name: Run training script
      shell: bash /home/cc/trainer/run_training.sh
      args:
        chdir: /home/cc/trainer/

# === SERVING NODE SETUP ===
- name: Setup and Run Model Server
  hosts: serving_node
  become: true
  tasks:
    - name: Copy server code
      copy:
        src: ../server/
        dest: /home/cc/server/
        owner: cc
        group: cc
        mode: '0755'

    - name: Run server script
      shell: bash /home/cc/server/run_server.sh
      args:
        chdir: /home/cc/server/
